name: Release plugin to testing

on:
  workflow_dispatch: 

env:
  PLUGIN_NAME: PlayerTrack
  PERSONAL_PLUGIN_REPO: kalilistic/DalamudPlugins
  GITHUB_TOKEN: ${{secrets.PAT}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Get release
        id: getrel
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{github.repository}}

      - name: Checkout DalamudPlugins
        uses: actions/checkout@v2
        with:
          repository: ${{env.PERSONAL_PLUGIN_REPO}}
          token: ${{secrets.PAT}}

      - name: Sync fork and set branch
        run: |
          git remote add upstream https://github.com/goatcorp/DalamudPlugins
          git pull upstream master
          git push
          git checkout -b ${{env.PLUGIN_NAME}}-Testing-${{steps.getrel.outputs.release}}

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          path: plugins/${{env.PLUGIN_NAME}}

      - name: Cleanup artifact
        run: |
          mkdir -p testing/${{env.PLUGIN_NAME}}/
          mv plugins/${{env.PLUGIN_NAME}}/artifact/* testing/${{env.PLUGIN_NAME}}/
          rm -rf plugins/${{env.PLUGIN_NAME}}/artifact

      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          add: --all
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          branch: ${{env.PLUGIN_NAME}}-Testing-${{steps.getrel.outputs.release}}
          message: ${{env.PLUGIN_NAME}} -> ${{steps.getrel.outputs.release}} [Testing]
          pull_strategy: NO-PULL
          
      - name: Create PR
        run: |
          git config --local --add remote.upstream.gh-resolved base
          gh pr create --title "[Testing] ${{env.PLUGIN_NAME}} ${{steps.getrel.outputs.release}}" --body "nofranz"